name: task_manager
description: A comprehensive task management application with advanced features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.2.2
  
  # Core Dependencies
  cupertino_icons: ^1.0.2
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # State Management & Storage
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Notifications
  awesome_notifications: ^0.10.1


  
  # Date & Time
  intl: ^0.20.2
  
  # Export Functionality
  pdf: ^3.10.7
  csv: ^6.0.0
  
  # Email & Sharing
  share_plus: ^7.2.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # UI Enhancements
  flutter_slidable: ^3.0.1
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  
  # Biometric Authentication
  local_auth: ^2.1.7
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  
  # File Picker & Animations
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.0.0
  
  # Voice input
  speech_to_text: ^7.0.0
  
  # Audio recording
  record: ^5.0.4
  audioplayers: ^6.0.0
  
  # Ads
  google_mobile_ads: ^5.1.0
  
  # Connectivity
  connectivity_plus: ^6.0.5
  
dependency_overrides:
  record_linux: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

